# Generated by Django 4.2 on 2023-04-07 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zanr',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='zanr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Collection.Zanr'),
        ),
    ]
