# Generated by Django 4.2 on 2023-04-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0003_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=30, verbose_name='Tagy')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagy',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='tagy',
            field=models.ManyToManyField(to='Collection.Tag'),
        ),
    ]
